/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Week_01;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Administrator
 */
public class frm_PlayFair extends javax.swing.JFrame {

    /**
     * Creates new form frm_PlayFair
     */
    private PlayfairCipher playfairCipher;
    public frm_PlayFair() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_openFile = new javax.swing.JButton();
        btn_dec = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_plain = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_cipher = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txt_key = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_enc = new javax.swing.JButton();
        btn_GKM = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_matrix = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_openFile.setText("Open Ciphertext File");
        btn_openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openFileActionPerformed1(evt);
            }
        });

        btn_dec.setText("Decrypt");
        btn_dec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decActionPerformed1(evt);
            }
        });

        txt_plain.setColumns(20);
        txt_plain.setRows(5);
        jScrollPane1.setViewportView(txt_plain);

        txt_cipher.setColumns(20);
        txt_cipher.setRows(5);
        jScrollPane2.setViewportView(txt_cipher);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("PlayFair Cipher Demo");

        jLabel2.setText("plainText:");

        jLabel3.setText("cipherText:");

        jLabel4.setText("key:");

        btn_enc.setText("Encrypt");
        btn_enc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encActionPerformed(evt);
            }
        });

        btn_GKM.setText("Gennerate Key Matrix");
        btn_GKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GKMActionPerformed1(evt);
            }
        });

        txt_matrix.setColumns(20);
        txt_matrix.setRows(5);
        jScrollPane3.setViewportView(txt_matrix);

        jLabel5.setText("key matrix");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txt_key))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_GKM)
                                .addGap(57, 57, 57)
                                .addComponent(btn_enc)
                                .addGap(58, 58, 58)
                                .addComponent(btn_dec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(btn_openFile)
                                .addGap(27, 27, 27)))))
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_openFile)
                            .addComponent(btn_enc)
                            .addComponent(btn_dec)
                            .addComponent(btn_GKM))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_openFileActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openFileActionPerformed1
      
        // TODO add your handling code here:
        JFileChooser fileC= new JFileChooser();
        fileC.setFileFilter(new FileNameExtensionFilter("Text Files","txt"));
        int userSelection = fileC.showOpenDialog(this);
        if(userSelection==JFileChooser.APPROVE_OPTION){
            try( BufferedReader bffr= new BufferedReader(new FileReader(fileC.getSelectedFile()))){
                    JOptionPane.showMessageDialog(this, "file open successfully");
                    txt_cipher.read(bffr, null);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(this,"error"+e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_openFileActionPerformed1

    private void btn_decActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decActionPerformed1
        
        String ciphertext = txt_cipher.getText();
    String key = txt_key.getText();

    if (!ciphertext.isEmpty() && !key.isEmpty()) {
        playfairCipher = new PlayfairCipher(key);
        String plaintext = playfairCipher.decrypt(ciphertext);
        JOptionPane.showMessageDialog(this, "Decrypted successfully.");
        txt_plain.setText(plaintext);
    } else {
        JOptionPane.showMessageDialog(this, "Please enter ciphertext and key.");
    }
        
    }//GEN-LAST:event_btn_decActionPerformed1

    private void btn_encActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encActionPerformed
        String plaintext = txt_plain.getText();
    String key = txt_key.getText();

    if (!plaintext.isEmpty() && !key.isEmpty()) {
        playfairCipher = new PlayfairCipher(key);
        String ciphertext = playfairCipher.encrypt(plaintext);
        JOptionPane.showMessageDialog(this, "Encrypted successfully.");
        txt_cipher.setText(ciphertext);
        saveToFile(ciphertext);
    } else {
        JOptionPane.showMessageDialog(this, "Please enter plaintext and key.");
    }
    }//GEN-LAST:event_btn_encActionPerformed

     private void saveToFile(String content){
        JFileChooser fileC= new JFileChooser();
        FileNameExtensionFilter filter =new FileNameExtensionFilter("Text Files","txt");
        fileC.setFileFilter(filter);
        int userSelection = fileC.showOpenDialog(this);
        if(userSelection==JFileChooser.APPROVE_OPTION){
            try(FileWriter fw= new FileWriter(fileC.getSelectedFile()+ ".txt")){
                    fw.write(content);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(this,"error"+e.getMessage());
            }
          
    }
 }
    
    private void btn_GKMActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GKMActionPerformed1
        // TODO add your handling code here:
          String key = txt_key.getText();
    if (!key.isEmpty()) {
        playfairCipher = new PlayfairCipher(key);
        String keyMatrixString = playfairCipher.getKeyMatrixAsString();
        txt_matrix.setText(keyMatrixString);
    } else {
        JOptionPane.showMessageDialog(this, "Please enter key to generate key matrix.");
    }
    }//GEN-LAST:event_btn_GKMActionPerformed1

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_PlayFair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_PlayFair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_PlayFair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_PlayFair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_PlayFair().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GKM;
    private javax.swing.JButton btn_dec;
    private javax.swing.JButton btn_enc;
    private javax.swing.JButton btn_openFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txt_cipher;
    private javax.swing.JTextField txt_key;
    private javax.swing.JTextArea txt_matrix;
    private javax.swing.JTextArea txt_plain;
    // End of variables declaration//GEN-END:variables
}
