/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Week_03;

/**
 *
 * @author Administrator
 */
import java.io.File;
import java.io.FileWriter;
import java.io.FilterWriter;
import java.io.IOException;
import javax.swing.*;
import java.security.KeyPair;
import java.security.PublicKey;
import java.security.PrivateKey;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import java.security.Security;
public class frm_ECC extends javax.swing.JFrame {

    /**
     * Creates new form frm_ECC
     */
    private ECCCipher ecc;
    private PublicKey publicKey;
    private PrivateKey privateKey;
    public frm_ECC() {
        initComponents();
        ecc=new ECCCipher();
        Security.addProvider(new BouncyCastleProvider());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_generatekey = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_plaintext = new javax.swing.JTextArea();
        txt_publickey = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ciphertext = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txt_privatekey = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_decrypt = new javax.swing.JButton();
        btn_loadkey = new javax.swing.JButton();
        btn_encrypt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_generatekey.setText("Generate Key");
        btn_generatekey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generatekeyActionPerformed(evt);
            }
        });

        txt_plaintext.setColumns(20);
        txt_plaintext.setRows(5);
        jScrollPane1.setViewportView(txt_plaintext);

        jLabel1.setText("plain text");

        txt_ciphertext.setColumns(20);
        txt_ciphertext.setRows(5);
        jScrollPane2.setViewportView(txt_ciphertext);

        jLabel2.setText("Cipher text");

        jLabel4.setText("public key");

        jLabel5.setText("private key");

        btn_decrypt.setText("decrypt");
        btn_decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decryptActionPerformed(evt);
            }
        });

        btn_loadkey.setText("Loadkey");
        btn_loadkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadkeyActionPerformed(evt);
            }
        });

        btn_encrypt.setText("encrypt");
        btn_encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encryptActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Elliptic Curve Cryptography Demo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_publickey)
                            .addComponent(txt_privatekey)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(117, Short.MAX_VALUE)
                        .addComponent(btn_generatekey)
                        .addGap(18, 18, 18)
                        .addComponent(btn_encrypt)
                        .addGap(38, 38, 38)
                        .addComponent(btn_decrypt)
                        .addGap(63, 63, 63)
                        .addComponent(btn_loadkey)))
                .addGap(237, 237, 237))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txt_publickey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_privatekey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_generatekey)
                    .addComponent(btn_loadkey)
                    .addComponent(btn_decrypt)
                    .addComponent(btn_encrypt))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generatekeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generatekeyActionPerformed
        try {
        KeyPair keyPair = ecc.generateKeyPair();
        publicKey = keyPair.getPublic();
        privateKey = keyPair.getPrivate();

        txt_publickey.setText(Base64.getEncoder()
                .encodeToString(publicKey.getEncoded()));
        txt_privatekey.setText(Base64.getEncoder()
                .encodeToString(privateKey.getEncoded()));

        // Save public key to file
        JFileChooser publicKeyChooser = new JFileChooser();
        publicKeyChooser.setDialogTitle("Save Public Key File");
        int publicKeyChooserResult = publicKeyChooser.showSaveDialog(this);

        if (publicKeyChooserResult == JFileChooser.APPROVE_OPTION) {
            File publicKeyFile = publicKeyChooser.getSelectedFile();
            try (FileWriter writer = new FileWriter(publicKeyFile.getAbsolutePath())) {
                writer.write(Base64.getEncoder().encodeToString(publicKey.getEncoded()));
                JOptionPane.showMessageDialog(this,
                        "Public Key saved to file successfully.",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                        "Error saving Public Key file: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        // Save private key to file
        JFileChooser privateKeyChooser = new JFileChooser();
        privateKeyChooser.setDialogTitle("Save Private Key File");
        int privateKeyChooserResult = privateKeyChooser.showSaveDialog(this);

        if (privateKeyChooserResult == JFileChooser.APPROVE_OPTION) {
            File privateKeyFile = privateKeyChooser.getSelectedFile();
            try (FileWriter writer = new FileWriter(privateKeyFile.getAbsolutePath())) {
                writer.write(Base64.getEncoder().encodeToString(privateKey.getEncoded()));
                JOptionPane.showMessageDialog(this,
                        "Private Key saved to file successfully.",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                        "Error saving Private Key file: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    } catch (Exception ex) {
        Logger.getLogger(frm_ECC.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this,
                "Error generating ECC key pair: " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_generatekeyActionPerformed

    private void btn_encryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encryptActionPerformed
        try {
        String plaintext = txt_plaintext.getText();

        byte[] ciphertext = ecc.encrypt(plaintext, publicKey);

        txt_ciphertext.setText(Base64.getEncoder().encodeToString(ciphertext));

    } catch (Exception ex) {
        Logger.getLogger(frm_ECC.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this,
                "Error encrypting: " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_encryptActionPerformed

    private void btn_decryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decryptActionPerformed
       try {
        byte[] ciphertext = Base64.getDecoder().decode(txt_ciphertext.getText());

        String decryptedText = ecc.decrypt(ciphertext, privateKey);

        txt_plaintext.setText(decryptedText);

    } catch (Exception ex) {
        Logger.getLogger(frm_ECC.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this,
                "Error decrypting: " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_decryptActionPerformed

    private void btn_loadkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadkeyActionPerformed
        try {
        // Load public key from file
        JFileChooser publicKeyChooser = new JFileChooser();
        publicKeyChooser.setDialogTitle("Load Public Key File");
        int publicKeyChooserResult = publicKeyChooser.showOpenDialog(this);

        if (publicKeyChooserResult == JFileChooser.APPROVE_OPTION) {
            File publicKeyFile = publicKeyChooser.getSelectedFile();
            byte[] publicKeyBytes = Base64.getDecoder().decode(
                    new String(java.nio.file.Files.readAllBytes(publicKeyFile.toPath()))
            );

            publicKey = ECCCipher.loadPublicKey(publicKeyBytes);
            txt_publickey.setText(Base64.getEncoder()
                    .encodeToString(publicKey.getEncoded()));
        }

        // Load private key from file
        JFileChooser privateKeyChooser = new JFileChooser();
        privateKeyChooser.setDialogTitle("Load Private Key File");
        int privateKeyChooserResult = privateKeyChooser.showOpenDialog(this);

        if (privateKeyChooserResult == JFileChooser.APPROVE_OPTION) {
            File privateKeyFile = privateKeyChooser.getSelectedFile();
            byte[] privateKeyBytes = Base64.getDecoder().decode(
                    new String(java.nio.file.Files.readAllBytes(privateKeyFile.toPath()))
            );

            privateKey = ECCCipher.loadPrivateKey(privateKeyBytes);
            txt_privatekey.setText(Base64.getEncoder()
                    .encodeToString(privateKey.getEncoded()));
        }

    } catch (Exception ex) {
        Logger.getLogger(frm_ECC.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this,
                "Error loading keys: " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_loadkeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ECC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ECC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ECC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ECC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_ECC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_decrypt;
    private javax.swing.JButton btn_encrypt;
    private javax.swing.JButton btn_generatekey;
    private javax.swing.JButton btn_loadkey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_ciphertext;
    private javax.swing.JTextArea txt_plaintext;
    private javax.swing.JTextField txt_privatekey;
    private javax.swing.JTextField txt_publickey;
    // End of variables declaration//GEN-END:variables
}
