/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Week_03;

/**
 *
 * @author Administrator
 */
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
public class frm_RSA_AES extends javax.swing.JFrame {

    /**
     * Creates new form frm_RSA_AES
     */
    private RSA_AES_Cipher rsaCipher;
    public frm_RSA_AES() {
        initComponents();
        try{
            rsaCipher= new RSA_AES_Cipher();
        }catch(Exception ex){
            Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE,null,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btn_generatekey = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_decrypt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_plaintext = new javax.swing.JTextArea();
        btn_loadkey = new javax.swing.JButton();
        txt_publickey = new javax.swing.JTextField();
        btn_encrypt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ciphertext = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txt_privatekey = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("public key");

        btn_generatekey.setText("Generate Key");
        btn_generatekey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generatekeyActionPerformed(evt);
            }
        });

        jLabel5.setText("private key");

        btn_decrypt.setText("decrypt");
        btn_decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decryptActionPerformed(evt);
            }
        });

        txt_plaintext.setColumns(20);
        txt_plaintext.setRows(5);
        jScrollPane1.setViewportView(txt_plaintext);

        btn_loadkey.setText("Loadkey");
        btn_loadkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadkeyActionPerformed(evt);
            }
        });

        btn_encrypt.setText("encrypt");
        btn_encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encryptActionPerformed(evt);
            }
        });

        jLabel1.setText("plain text");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("RSA-AES Cipher Demo");

        txt_ciphertext.setColumns(20);
        txt_ciphertext.setRows(5);
        jScrollPane2.setViewportView(txt_ciphertext);

        jLabel2.setText("Cipher text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_publickey)
                    .addComponent(txt_privatekey)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_generatekey)
                .addGap(39, 39, 39)
                .addComponent(btn_encrypt)
                .addGap(52, 52, 52)
                .addComponent(btn_decrypt)
                .addGap(51, 51, 51)
                .addComponent(btn_loadkey)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txt_publickey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_privatekey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_generatekey)
                    .addComponent(btn_loadkey)
                    .addComponent(btn_decrypt)
                    .addComponent(btn_encrypt))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String readFile(File file) throws IOException {
    StringBuilder contentBuilder = new StringBuilder();

    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        String line;

        while ((line = br.readLine()) != null) {
            contentBuilder.append(line).append("\n");
        }
    }

    return contentBuilder.toString();
}
    
    private void btn_generatekeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generatekeyActionPerformed
       try {
        rsaCipher = new RSA_AES_Cipher();
        txt_publickey.setText(rsaCipher.getPublicKey().toString());
        txt_privatekey.setText(rsaCipher.getPrivateKey().toString());
        JFileChooser publicKeyChooser = new JFileChooser();
        publicKeyChooser.setDialogTitle("Save Public Key File");
        int publicKeyResult = publicKeyChooser.showSaveDialog(this);
        if (publicKeyResult == JFileChooser.APPROVE_OPTION) {

            File publicKeyFile = publicKeyChooser.getSelectedFile();

            try (FileWriter writer = new FileWriter(publicKeyFile.getAbsolutePath())) {
                writer.write(rsaCipher.getPublicKey().toString());
                JOptionPane.showMessageDialog(
                        this,
                        "Public Key saved to file successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(
                        this,
                        "Error saving Public Key file: " + ex.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }

        JFileChooser privateKeyChooser = new JFileChooser();
        privateKeyChooser.setDialogTitle("Save Private Key File");

        int privateKeyResult = privateKeyChooser.showSaveDialog(this);
        if (privateKeyResult == JFileChooser.APPROVE_OPTION) {

            File privateKeyFile = privateKeyChooser.getSelectedFile();

            try (FileWriter writer = new FileWriter(privateKeyFile.getAbsolutePath())) {
                writer.write(rsaCipher.getPrivateKey().toString());
                JOptionPane.showMessageDialog(
                        this,
                        "Private Key saved to file successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(
                        this,
                        "Error saving Private Key file: " + ex.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    } catch (Exception ex) {
        Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(
                this,
                "Error generating RSA key pair: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btn_generatekeyActionPerformed

    private void btn_decryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decryptActionPerformed
        try {
        byte[] combined = txt_ciphertext.getText().getBytes(StandardCharsets.ISO_8859_1);
        String decryptedText = rsaCipher.decrypt(combined);
        txt_plaintext.setText(decryptedText);
    } catch (IllegalBlockSizeException | BadPaddingException ex) {
        Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(
                this,
                "Error decrypting: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    } catch (Exception ex) {
        Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(
                this,
                "Error decrypting: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btn_decryptActionPerformed

    private void btn_loadkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadkeyActionPerformed
       try {

        JFileChooser publicKeyChooser = new JFileChooser();
        publicKeyChooser.setDialogTitle("Load Public Key File");

        int publicKeyChooserResult = publicKeyChooser.showOpenDialog(this);

        if (publicKeyChooserResult == JFileChooser.APPROVE_OPTION) {
            File publicKeyFile = publicKeyChooser.getSelectedFile();
            String publicKeyContent = readFile(publicKeyFile);
            txt_publickey.setText(publicKeyContent);
        }

        JFileChooser privateKeyChooser = new JFileChooser();
        privateKeyChooser.setDialogTitle("Load Private Key File");

        int privateKeyChooserResult = privateKeyChooser.showOpenDialog(this);

        if (privateKeyChooserResult == JFileChooser.APPROVE_OPTION) {
            File privateKeyFile = privateKeyChooser.getSelectedFile();
            String privateKeyContent = readFile(privateKeyFile);
            txt_privatekey.setText(privateKeyContent);
        }

    } catch (HeadlessException | IOException ex) {
        Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(
                this,
                "Error loading keys: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btn_loadkeyActionPerformed

    private void btn_encryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encryptActionPerformed
       try {
        String plaintext = txt_plaintext.getText();
        byte[] encryptedBytes = rsaCipher.encrypt(plaintext);
        String encryptedText = new String(encryptedBytes,StandardCharsets.ISO_8859_1);
        txt_ciphertext.setText(encryptedText);
    } catch (IllegalBlockSizeException | BadPaddingException ex) {
        Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(
                this,
                "Error encrypting: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    } catch (Exception ex) {
        Logger.getLogger(frm_RSA_AES.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(
                this,
                "Error encrypting: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btn_encryptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_RSA_AES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_RSA_AES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_RSA_AES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_RSA_AES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_RSA_AES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_decrypt;
    private javax.swing.JButton btn_encrypt;
    private javax.swing.JButton btn_generatekey;
    private javax.swing.JButton btn_loadkey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_ciphertext;
    private javax.swing.JTextArea txt_plaintext;
    private javax.swing.JTextField txt_privatekey;
    private javax.swing.JTextField txt_publickey;
    // End of variables declaration//GEN-END:variables
}
